/**/*:
  ros__parameters:
    broker:
      host: 134.130.20.225 #127.0.0.1
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics: 
          - /ros_unsegmented 
          - /ros_segmentation_response 

        /ros_unsegmented:
          mqtt_topic: mqtt_segmentation_request
          ros_type: sensor_msgs/msg/Image
          advanced:
            ros:
              queue_size: 10
              qos:
                reliability: reliable
                durability: transient_local
            mqtt:
              qos: 1
              retained: false

        /ros_segmentation_response:
          mqtt_topic: mqtt_segmentation_response 
          ros_type: sensor_msgs/msg/Image
          advanced:
            ros:
              queue_size: 10
              qos:
                reliability: reliable
                durability: transient_local
            mqtt:
              qos: 1
              retained: false

      mqtt2ros:
        mqtt_topics: 
          - mqtt_segmentation_response
          - mqtt_segmentation_request

        mqtt_segmentation_response:
          ros_topic: /ros_segmented
          ros_type: sensor_msgs/msg/Image
          advanced:
            mqtt:
              qos: 1
            ros:
              queue_size: 10
              latched: false
              qos:
                reliability: reliable
                durability: transient_local

        mqtt_segmentation_request:
          ros_topic: /ros_segmentation_request
          ros_type: sensor_msgs/msg/Image
          advanced:
            mqtt:
              qos: 1
            ros:
              queue_size: 10
              latched: false
              qos:
                reliability: reliable
                durability: transient_local
